---
roles:
  - name: kameshsampath.kind
    src: https://github.com/kameshsampath/ansible-role-kind
  - name: kameshsampath.minikube
    src: https://github.com/kameshsampath/ansible-role-minikube
  - name: kameshsampath.k8s_app_spices
    src: https://github.com/kameshsampath/ansible-role-kubernetes-spices
collections:
  - name: community.kubernetes
    version: 0.11.1
